CREATE TABLE prestadores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    descricao TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE setores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE motivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    modelo VARCHAR(255),
    numero_serie VARCHAR(255),
    prestador_id BIGINT NOT NULL REFERENCES prestadores(id),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_equipamento_nome_prestador UNIQUE (nome, prestador_id)
);

CREATE TABLE chamados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_ch VARCHAR(50),
    prestador_id BIGINT NOT NULL REFERENCES prestadores(id),
    equipamento_id BIGINT REFERENCES equipamentos(id),
    setor_id BIGINT NOT NULL REFERENCES setores(id),
    motivo_id BIGINT NOT NULL REFERENCES motivos(id),
    descricao_atendimento TEXT NOT NULL,
    data_abertura TIMESTAMP(6) NOT NULL,
    data_fechamento TIMESTAMP(6),
    tempo_atendimento_minutos INTEGER,
    status VARCHAR(255) NOT NULL,
    conceito VARCHAR(255),
    observacao TEXT,
    ocorrencias_mesmo_servico INTEGER DEFAULT 0,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE chamado_historico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chamado_id BIGINT NOT NULL REFERENCES chamados(id),
    status_de VARCHAR(255),
    status_para VARCHAR(255) NOT NULL,
    observacao TEXT,
    alterado_em TIMESTAMP(6)
);

CREATE INDEX idx_chamados_status ON chamados(status);
CREATE INDEX idx_chamados_prestador ON chamados(prestador_id);
CREATE INDEX idx_chamados_equipamento ON chamados(equipamento_id);
CREATE INDEX idx_chamados_setor ON chamados(setor_id);
CREATE INDEX idx_chamados_motivo ON chamados(motivo_id);
CREATE INDEX idx_chamados_abertura ON chamados(data_abertura);
CREATE INDEX idx_historico_chamado ON chamado_historico(chamado_id);
